### ISSUE TITLE
Feature request: Export processed data

### ISSUE THREAD

**Issue by reinzor** [reinzor/timeline-exporter#4]
- Export km
- Export miles
- Export duration as hr:min:sec

**Comment by JohnBigfield** [comment]
Hi Rein, thanks for looking into that.  

I'm a self-employed carpenter/handyman working for different customers at different locations in Amsterdam. For 3 years I've been using Google timeline to trace back 1 day at the time where I've been working and for how long. Very time-consuming, so that's why I'm so pleased with your tool. I'm wondering why you wanted to make this tool.

I played with TE a bit more and tried to do an export over a longer period of time, like the year 2018 or 2019. But somehow Google doesn't like hat. It seems like the requests to Google are made while I'm putting the date range in. I got messages from Google which said something about too many requests and wanted to know if I'm a robot (I've seen this behavior mentioned in other posts too). On other occasions, the tool just hangs and I have to start over. 

I've tried it like this: Start with the focus on "day" and put in the beginning of the date range I want. Then I switch to "range". The tool fills in the date of today and immediately starts grabbing but locks up prematurely. It might be that that range is too large to grab, but trying to choose an earlier end date results either in a lockup or Google complaining. 

Maybe it is possible to make it so that you choose a date range first, max 1 year at a time, without sending requests to Google just jet. Then send that request with an added GO button. 

I've managed to export a bit more than a year, 1 Jan 2020 till now, so 1 year at the time should be fine. 

I hope this input is useful to you. I think your tool opens up even more possibilities. I'm very happy already though.

**Comment by reinzor** [comment]
Hi @JohnBigfield , thanks for the detailed usage report. I opened a new issue for the `GO` button functionality you mentioned.

The main motivation for the tool was the hassle of filling in timesheet based on gmaps timeline data. This allows me to easy create timesheets of the time worked at a specific location or mileage reports.

**Comment by reinzor** [comment]
Fixed by https://github.com/reinzor/timeline-exporter/commit/b2d8f48c962cbb20099e4303b14229100873b51b

**Comment by JohnBigfield** [comment]
Hi Rein, that would be nice.

Be aware that it only seems to work well when while putting in a date range, there are no requests going to Google until the GO button is used.

I’ve checked this as a workaround by disconnecting from internet before putting in the required date range  minus one day (01 jan - 30 dec), then connect to internet and shift one day up (31 dec). It still takes a while for 1 year data but it works without lockup or errors.

Good luck

John Grootveld

**Comment by reinzor** [comment]
Not that this should be configured here:

![image](https://user-images.githubusercontent.com/4176023/114542373-24008100-9c58-11eb-9a5c-4d0613902a90.png)

**Comment by JohnBigfield** [comment]
Ah yes, found it, I didn't expect it to be there. Love it. Works like a charm. Thanks
